### ISSUE TITLE
Feature: add a prefix to elastic index 

### ISSUE THREAD

**Issue by aladjadj** [bmwcarit/zubbi#37]
Issue: 
if we want to use a shared cluster, it's necessary to scope indexes with prefix.

**Comment by felix-schmidt** [comment]
Hi and thanks for your request!

If I understand this correctly, it's about a "generic" prefix for all Zubbi-related indexes, right? To avoid name-clashes if an index with the same name is already used by another part of the system. But it's not related to the clustering itself.

**Comment by aladjadj** [comment]
Yes, that right 👌

**Comment by felix-schmidt** [comment]
I tried to make the index configurable via the pattern described in https://elasticsearch-dsl.readthedocs.io/en/latest/persistence.html#index. Unfortunately, this only works for the initialization part of the documents, so the custom indices are created correctly. The document's `save()` method, however, always falls back to the index defined in the document's index-meta e.g.:

```python
class AnsibleRole(Block):
    ...

    class Index:
        name = "ansible-roles"
```

If I remove this index-meta completely, elasticsearch-dsl falls back to a wildcard index `*` and won't save the documents at all:

```python
raise ValidationException('You cannot write to a wildcard index.')
    elasticsearch_dsl.exceptions.ValidationException: You cannot write to a wildcard index.
```

There are already two issues reported to elasticsearch-dsl describing the same behaviour https://github.com/elastic/elasticsearch-dsl-py/issues/1121 and https://github.com/elastic/elasticsearch-dsl-py/issues/1091 and a fix is proposed but not merged yet https://github.com/elastic/elasticsearch-dsl-py/pull/1099.

I also tried to inject the index-name directly in the document's `save()` method, but this also didn't do the trick as we are mostly using the `elasticsearch.helpers.bulk()` method which then also would need to be changed.

If this feature is not too urgent for you, I would propose to wait until the issue above is solved.

Another option would be to add the index explicitly to all `document.init()` and `document.save()` methods, but this looks more like a hack than a solution 😄

**Comment by aladjadj** [comment]
Thx for your feedback, it's not simple to implement.
I looking for a solution with the environment variables and constant

WIP: https://github.com/leboncoin/zubbi/pull/1

**Comment by felix-schmidt** [comment]
@aladjadj I tried a different way. Looks like https://github.com/bmwcarit/zubbi/pull/41 does the trick. I would call this also a hack but I find this less intrusive than the solution via environment variables.

I'm currently working on some tests.

**Comment by aladjadj** [comment]
👌🔥
